name: Security check - Bandit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    name: Python ${{ matrix.os }} 

    steps:
    - uses: actions/checkout@v3

    - name: Security check - Bandit
      uses: ioggstream/bandit-report-artifacts@v1.7.4
      with:
        project_path: .
        ignore_failure: true

    # This is optional
    - name: Security check report artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Security report
        path: output/security_report.txt
